# Multilayer Perceptron for Iris dataset

- Nguyễn Hữu Vũ 
- Nhóm nghiên cứu về AI đại học Bách Khoa Tp. Hồ Chí Minh

In [38]:

from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np

In [39]:
# Load the iris dataset
iris = datasets.load_iris()

# Create our X and y data
X = iris.data
y = iris.target

## 1) Khám phá dữ liệu

In [40]:
X.shape

(150, 4)

In [41]:
y.shape

(150,)

In [42]:
X[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [43]:
# View the first five observations of our y data
y[:5]

array([0, 0, 0, 0, 0])

In [44]:
# Split the data into 70% training data and 30% test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [45]:
X_train[:5]

array([[5.5, 3.5, 1.3, 0.2],
       [5.5, 2.5, 4. , 1.3],
       [7.7, 2.8, 6.7, 2. ],
       [4.9, 3.6, 1.4, 0.1],
       [6.8, 3. , 5.5, 2.1]])

## 2) Chuẩn bị dữ liệu

In [46]:
# Train the scaler, which standarizes all the features to have mean=0 and unit variance
sc = StandardScaler()
sc.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [47]:
# Apply the scaler to the X training data
X_train_std = sc.transform(X_train)

# Apply the SAME scaler to the X test data
X_test_std = sc.transform(X_test)

In [48]:
X_train_std[:5]

array([[-0.55220855,  1.01665721, -1.54515283, -1.43513942],
       [-0.55220855, -1.23543154,  0.05532517,  0.0568372 ],
       [ 2.22083875, -0.55980492,  1.65580316,  1.00627688],
       [-1.30849418,  1.24186608, -1.48587587, -1.57077366],
       [ 1.08641031, -0.10938717,  0.94447961,  1.14191111]])

In [49]:
X_test_std[:5]

array([[ 0.07802947, -1.91105817,  0.05532517, -0.35006551],
       [-1.18244658,  1.01665721, -1.54515283, -1.29950518],
       [-1.56058939,  0.34103058, -1.54515283, -1.43513942],
       [-1.05639897,  1.46707496, -1.4265989 , -1.16387094],
       [ 0.58221989, -0.78501379,  0.82592568,  0.87064264]])

## 3) Xây dựng model Perceptron

In [50]:
# Create a perceptron object with the parameters: 40 iterations (epochs) over the data, and a learning rate of 0.1
ppn = Perceptron(max_iter=40, eta0=0.1, random_state=0)


In [51]:

# Train the perceptron
ppn.fit(X_train_std, y_train)

Perceptron(alpha=0.0001, class_weight=None, early_stopping=False, eta0=0.1,
           fit_intercept=True, max_iter=40, n_iter_no_change=5, n_jobs=None,
           penalty=None, random_state=0, shuffle=True, tol=0.001,
           validation_fraction=0.1, verbose=0, warm_start=False)

In [52]:
#The actual number of iterations to reach the stopping criterion. For multiclass fits, it is the maximum over every binary fit.
ppn.n_iter_ 

10

##### Prediction

In [53]:
# Apply the trained perceptron on the X data to make predicts for the y test data
y_pred = ppn.predict(X_test_std)
y_pred

array([1, 0, 0, 0, 1, 2, 1, 0, 0, 1, 0, 0, 0, 2, 1, 1, 0, 2, 1, 1, 1, 0,
       0, 2, 1, 0, 0, 0, 0, 2, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 2, 1, 1, 1,
       2])

In [54]:
# View the accuracy of the model, which is: 1 - (observations predicted wrong / total observations)
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

Accuracy: 0.76


## 4) Xây dựng model MLPClassifier

In [55]:
from sklearn.neural_network import MLPClassifier

clf = MLPClassifier(hidden_layer_sizes=(8,5 ), activation='tanh', solver='sgd', 
                    alpha=0.0000001, batch_size=4, learning_rate='constant', learning_rate_init=0.005, 
                    power_t=0.5, max_iter=500, shuffle=True, random_state=11, tol=0.00001, 
                    verbose=True, warm_start=False, momentum=0.8, nesterovs_momentum=True, 
                    early_stopping=False, validation_fraction=0.2, 
                    beta_1=0.9, beta_2=0.999, epsilon=1e-08)


In [56]:

# Train the perceptron
clf.fit(X_train_std, y_train)

Iteration 1, loss = 1.11656164
Iteration 2, loss = 0.89378279
Iteration 3, loss = 0.75698460
Iteration 4, loss = 0.66481429
Iteration 5, loss = 0.59141086
Iteration 6, loss = 0.53828737
Iteration 7, loss = 0.49039381
Iteration 8, loss = 0.45360913
Iteration 9, loss = 0.42078052
Iteration 10, loss = 0.39061059
Iteration 11, loss = 0.36400503
Iteration 12, loss = 0.33877937
Iteration 13, loss = 0.31626020
Iteration 14, loss = 0.29304906
Iteration 15, loss = 0.27336776
Iteration 16, loss = 0.25418985
Iteration 17, loss = 0.23754278
Iteration 18, loss = 0.22313258
Iteration 19, loss = 0.20886941
Iteration 20, loss = 0.19783223
Iteration 21, loss = 0.18552644
Iteration 22, loss = 0.17731192
Iteration 23, loss = 0.17013853
Iteration 24, loss = 0.16229842
Iteration 25, loss = 0.15363641
Iteration 26, loss = 0.14623811
Iteration 27, loss = 0.14116761
Iteration 28, loss = 0.13758311
Iteration 29, loss = 0.13212494
Iteration 30, loss = 0.12992315
Iteration 31, loss = 0.12433824
Iteration 32, los

MLPClassifier(activation='tanh', alpha=1e-07, batch_size=4, beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(8, 5), learning_rate='constant',
              learning_rate_init=0.005, max_fun=15000, max_iter=500,
              momentum=0.8, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=11, shuffle=True, solver='sgd',
              tol=1e-05, validation_fraction=0.2, verbose=True,
              warm_start=False)

In [57]:
clf.classes_ 

array([0, 1, 2])

In [58]:
clf.n_layers_ 

4

In [59]:
clf.n_outputs_ 

3

In [60]:
clf.out_activation_ 

'softmax'

- 1 input, 2 hidden, 1 ouput: => 4
- Thông thường trong Neural Networks, sẽ ko tính input layers, nên  trong Neural Networks, trường hợp này số Layers sẽ là 3

In [61]:
# Evaluate acuracy on test data
score = clf.score(X_test_std,y_test)
print("Acuracy (on test set) = ", score)

Acuracy (on test set) =  0.9555555555555556


- Ta thấy chỉ cần tăng #Layers, #Units độ chính xác sẽ tăng cao